name: .NET Build and Test

on:
  workflow_call:
    inputs:
      configuration:
        description: 'Build configuration'
        required: false
        default: 'Release'
        type: string
      version:
        description: 'Package/application version'
        required: true
        type: string
      os:
        description: 'Operating system to run on'
        required: false
        default: 'ubuntu-latest'
        type: string

permissions:
  checks: write

jobs:
  build:
    name: 🏗️ Build and test

    runs-on: ${{ inputs.os }}

    env:
      ARTIFACTS_PATH: ${{ github.workspace }}/.artifacts/
      BINLOG_PATH: ${{ github.workspace }}/.artifacts/binlogs/
      TESTRESULTS_PATH: ${{ github.workspace }}/.artifacts/testresults/
      COVERAGEREPORT_PATH: ${{ github.workspace }}/.artifacts/coveragereports/
      NUGET_XMLDOC_MODE: skip
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      TERM: xterm


    steps:
      - uses: actions/checkout@v6
        name: 🛒 Checkout code
        with:
          filter: blob:none

      - name: 🛠️ Setup .NET
        uses: actions/setup-dotnet@v5

      - name: 📦 Cache NuGet packages
        uses: actions/cache@v4
        if: |
          github.event_name == 'pull_request' ||
          (github.ref_type == 'branch' && github.ref_name != github.event.repository.default_branch)
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('global.json', '**/*.props', '**/*.targets', '**/*.csproj') }}

      - name: 📥 Restore dependencies
        id: restore
        run: |
          dotnet restore \
            --artifacts-path ${{ env.ARTIFACTS_PATH }} \
            --property:Version=${{ inputs.version }} \
            --verbosity:minimal \
            -bl:${{ env.BINLOG_PATH }}/restore.binlog

      - name: 🏗️ Build
        id: build
        run: |
          dotnet build \
            --no-restore \
            --configuration ${{ inputs.configuration }} \
            --property:Version=${{ inputs.version }} \
            --verbosity:minimal \
            --artifacts-path ${{ env.ARTIFACTS_PATH }} \
            -bl:${{ env.BINLOG_PATH }}/build.binlog

      - name: 🧪 Test
        id: test
        run: |
          dotnet test \
            --no-build \
            --configuration ${{ inputs.configuration }} \
            --property:Version=${{ inputs.version }} \
            --verbosity:minimal \
            --property:ArtifactsPath=${{ env.ARTIFACTS_PATH }} \
            -bl:${{ env.BINLOG_PATH }}/test.binlog \
            --output Detailed \
            --results-directory ${{ env.TESTRESULTS_PATH }}

      - name: 📄 Publish test results
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() && steps.test.outcome != 'skipped' }}
        with:
          name: Test Results
          path: ${{ env.TESTRESULTS_PATH }}/*.trx
          reporter: dotnet-trx

      - name: 📊 ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@v5
        id: reportgenerator
        if: ${{ !cancelled() && steps.test.outcome != 'skipped' }}        
        with:
          reports: '${{ env.TESTRESULTS_PATH }}/*.cobertura.xml'
          targetdir: ${{ env.COVERAGEREPORT_PATH }}
          reporttypes: HTML;MarkdownSummaryGithub

      - name: 📝 Publish coverage summary
        if: ${{ steps.reportgenerator.outcome == 'success' }}      
        run: cat ${{ env.COVERAGEREPORT_PATH }}/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
        shell: bash
  
      - name: 📤 Publish code coverage results
        if: ${{ steps.reportgenerator.outcome == 'success' }}      
        uses: actions/upload-artifact@v6
        with:
          name: CoverageReport-${{ github.job }}
          path: ${{ env.COVERAGEREPORT_PATH }}         

      - name: 📤 Publish binlogs (on failure)
        uses: actions/upload-artifact@v6
        if: ${{ steps.restore.outcome == 'failure' || steps.build.outcome == 'failure' || steps.test.outcome == 'failure' || runner.debug }}
        with:
          name: Binlogs-${{ github.job }}
          path: ${{ env.BINLOG_PATH }}

      - name: 📤 Publish test artifacts (on failure)
        uses: actions/upload-artifact@v6
        if: ${{ steps.test.outcome == 'failure' || runner.debug }}
        with:
          name: TestResults-${{ github.job }}
          path: ${{ env.TESTRESULTS_PATH }}
