name: .NET
run-name: >-
  0.0.${{ github.run_number }}
  ${{
    github.event_name == 'pull_request'
      && format('-pr{0}', github.event.pull_request.number)
      || github.ref_type == 'branch'
      && format('-{0}', replace(github.ref_name, '/', '-'))
      || ''
  }}

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Build configuration'
        required: false
        default: 'Release'
        type: string

permissions:
  checks: write

jobs:
  build:
    uses: ./.github/workflows/dotnet.yml
    with:
      configuration: ${{ inputs.configuration || 'Release' }}
